# -*- coding: utf-8 -*-
"""ejecutar job spark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y5OoaLROm2_BYWeonIRGudR7yfukOYME
"""

from pyspark import SparkContext
sc = SparkContext("local", "NumericApp")

# 🧭 Paso 1: Carga un RDD numérico desde una lista
numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
rdd_numerico = sc.parallelize(numeros)

# 📜 Paso 2: Aplica una o más transformaciones
# Primero, filtramos para quedarnos solo con los números pares.
rdd_pares = rdd_numerico.filter(lambda x: x % 2 == 0)

# Luego, transformamos cada número par elevándolo al cuadrado.
rdd_cuadrados = rdd_pares.map(lambda x: x * x)

# ⏳ Paso 3: Confirma que aún no se ha ejecutado nada
# Si ejecutas este código hasta aquí, Spark no ha procesado ningún dato.
# Solo ha construido un "plan" o DAG (Grafo Acíclico Dirigido) de lo que debe hacer.
# 'rdd_cuadrados' es solo un puntero a este plan, no contiene el resultado.
print("Hasta ahora solo se ha definido el plan (DAG). Aún no se inicia el Job.")
print('-' * 70)

# 💥 Paso 4: Ejecuta una acción como sum()
# La acción 'sum()' DESENCADENA la ejecución del Job.
# Spark toma el DAG, lo optimiza y lo envía al clúster para su cómputo.
suma_total = rdd_cuadrados.sum()

# Ahora sí tenemos un resultado final.
print(f"El Job se ha ejecutado. La suma de los cuadrados de los pares es: {suma_total}")
# Resultado esperado: 4 + 16 + 36 + 64 + 100 = 220

sc.stop()