# -*- coding: utf-8 -*-
"""explora dataframe con sparkSQL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nvgV-Kcyt0-2NfXTWiw1P2y0OK0PEANM
"""

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("ReadCSV").getOrCreate()

df_spark = spark.read.format("csv").option("header", "true").option("sep", ";").load("/content/1. datos_agricolas.csv")

df_spark.show()
df_spark.printSchema()
df_spark.describe().show()

df_spark.createOrReplaceTempView("agricultural_data")

query_filtered = spark.sql("SELECT * FROM agricultural_data WHERE Cultivo = 'Tomate'")
query_filtered.show()

query_grouped = spark.sql("SELECT `Regi�n`, AVG(`Producci�n_Ton`) as Avg_Produccion FROM agricultural_data GROUP BY `Regi�n`")
query_grouped.show()

query_ordered = spark.sql("SELECT * FROM agricultural_data ORDER BY Utilidad DESC")
query_ordered.show()