# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16fZTq6WlTcrsQpFSlDSRbVTaJok3L86z
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt

# Datos
data = pd.DataFrame({
    'Antiguedad': [5, 3, 7, 2, 6, 4, 8, 1],
    'Kilometraje': [50000, 30000, 70000, 25000, 60000, 40000, 80000, 15000],
    'Puertas': [4, 2, 4, 2, 4, 2, 4, 2],
    'Precio': [12000, 15000, 9000, 16000, 11000, 14000, 8000, 17000]
})


# Separar variables
X = data[['Antiguedad', 'Kilometraje', 'Puertas']]
y = data['Precio']

# Entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Modelo
modelo = LinearRegression()
modelo.fit(X_train, y_train)

# Predicciones
y_pred = modelo.predict(X_test)

# Métricas
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5
r2 = r2_score(y_test, y_pred)

# Resultados
print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R²: {r2:.2f}")

# Coeficientes
coef = pd.DataFrame({'Variable': X.columns, 'Coeficiente': modelo.coef_})
print(coef)

# Gráfico
plt.scatter(y_test, y_pred)
plt.plot([y.min(), y.max()], [y.min(), y.max()], color='red', linestyle='--')
plt.xlabel("Precio Real")
plt.ylabel("Precio Predicho")
plt.title("Comparación Precio Real vs Predicho")
plt.grid()
plt.savefig("precio_real_vs_predicho.png")
plt.show()